### ISSUE TITLE
Ko administrator gleda 1 skupino (groups.view) naj so imena uporabnikov povezave do njihovih profilov

### ISSUE THREAD

**Issue by zigacernigoj** [lavrinec/SMRPO-is#7]
Ko administrator gleda eno skupino (groups.show), naj bodo [ime priimek] povezave do profilov uporabnikov - tako administratorja razbremeniš pri iskanju uporabnikov, če ve (samo) skupino, ne pa natančno uporabnika.

**Comment by glumacm** [comment]
Če mislim pravilno potem je sedaj to Done. Sedaj lahko administrator pride na podrobnosti skupine in na imenu in priimku uporabnika je možno klikniti kar sproži preusmeritev na detail o uporabniku na katerega smo ravnokar kliknili.
